title: UGent Business Informatics
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The department of Management Information science and Operations Management 
  is part of the nine departments which are effective within the faculty of 
  Economy and Business Management of Ghent University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://exampe.com
# twitter_username: jekyllrb
# github_username:  jekyll
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
